In [1]:
import pandas as pd
import numpy as np

In [3]:
author = pd.read_excel('../crwaling/author_detail.xlsx')

In [4]:
author

                        authors      born  death born_area  sex        job
0                           나예리       NaN    NaN       NaN   여자        만화가
1                           이문열     17708    NaN     서울특별시   남자        소설가
2                         조애너 콜     16295  44024    미국 뉴저지   여자     어린이 작가
3                           이호백  1962년 출생    NaN        서울   남자  화가, 출판사대표
4                           권정생     13768  39219     일본 도쿄   남자      아동문학가
...                         ...       ...    ...       ...  ...        ...
23028                    메인 스트릿       NaN    NaN       NaN  NaN        NaN
23029  로맨틱 카우치 (Romantic Couch)       NaN    NaN       NaN  NaN        NaN
23030                       한예슬       NaN    NaN       NaN  NaN        NaN
23031                       오지호     27864    NaN        한국  NaN         배우
23032                       박한별     31003    NaN        서울   여자         배우

[23033 rows x 6 columns]

In [6]:
datadf = pd.read_csv('../title-author.csv')

In [13]:
datadf['author']

0                        오비디우스 저/이윤기 역 | 민음사 | 1998년 08월
1                               김동인 등저 | 민음사 | 2000년 10월
2                        백범영 그림/송성욱 편역 | 민음사 | 2004년 04월
3                 비톨트 곰브로비치 저/임미경,윤진 역 | 민음사 | 2004년 05월
4                    비톨트 곰브로비치 저/임미경 역 | 민음사 | 2004년 05월
                             ...
456                    이사벨 아옌데 저/권미선 역 | 민음사 | 2003년 07월
457             가브리엘 가르시아 마르케스 저/조구호 역 | 민음사 | 2000년 01월
458                      요한 볼프강 폰 괴테 저 | 민음사 | 1999년 03월
459       프랑수아즈 사강,버지니아 울프 저/김남주,이미애 역 | 민음사 | 0001년 01월
460    나다니엘 호손,F. 스콧 피츠제럴드,제롬 데이비드 샐린저 저/김욱동,공경희 역 | ...
Name: author, Length: 461, dtype: object

In [20]:
datadf.loc[datadf['작가/번역'].isnull(), '작가/번역'] = ''

In [15]:
datadf['작가'] = ''

In [29]:
for i in range(len(datadf)):
    if ' 저' in datadf.loc[i, '작가/번역']:
        datadf.loc[i, '작가'] = datadf.loc[i, '작가/번역'].split(' 저')[0]

In [33]:
datadf[(datadf['작가/번역'].str.contains(' 역')) & (~datadf['작가/번역'].str.contains('/'))]

,title,author,page,작가/번역,출판사,출간일,작가
38,바덴바덴에서의 여름,이장욱 역 | 민음사 | 2006년 04월,http://www.yes24.com/Product/Goods/1988702,이장욱 역,민음사,2006년 04월,
60,구덩이,정보라 역 | 민음사 | 2007년 08월,http://www.yes24.com/Product/Goods/2663475,정보라 역,민음사,2007년 08월,
67,중국신화전설 1,김선자 역 | 민음사 | 1999년 02월,http://www.yes24.com/Product/Goods/1270,김선자 역,민음사,1999년 02월,
78,중국신화전설 2,김선자 역 | 민음사 | 1999년 02월,http://www.yes24.com/Product/Goods/1271,김선자 역,민음사,1999년 02월,
86,괴테와의 대화 1,장희창 역 | 민음사 | 2008년 05월,http://www.yes24.com/Product/Goods/2944911,장희창 역,민음사,2008년 05월,
87,괴테와의 대화 2,장희창 역 | 민음사 | 2008년 05월,http://www.yes24.com/Product/Goods/2944919,장희창 역,민음사,2008년 05월,
172,폭력적인 삶,이승수 역 | 민음사 | 2010년 07월,http://www.yes24.com/Product/Goods/4058418,이승수 역,민음사,2010년 07월,
252,불타는 평원,정창 역 | 민음사 | 2014년 08월,http://www.yes24.com/Product/Goods/14309718,정창 역,민음사,2014년 08월,
383,푸른 꽃,김재혁 역 | 민음사 | 2003년 05월,http://www.yes24.com/Product/Goods/364109,김재혁 역,민음사,2003년 05월,
392,질투,박이문 역 | 민음사 | 2003년 08월,http://www.yes24.com/Product/Goods/393733,박이문 역,민음사,2003년 08월,
404,뻬드로 빠라모,정창 역 | 민음사 | 2003년 12월,http://www.yes24.com/Product/Goods/423645,정창 역,민음사,2003년 12월,

In [34]:
# 예스24에서 작가 크롤링 안된거 수동 채우기~
datadf.loc[38, '작가'] = '레오니드 치프킨'
datadf.loc[60, '작가'] = '안드레이 플라토노프'
datadf.loc[86, '작가'] = '요한 페터 에커만'
datadf.loc[87, '작가'] = '요한 페터 에커만'
datadf.loc[172, '작가'] = '피에르 파올로 파솔리니'
datadf.loc[252, '작가'] = '후안 룰포'
datadf.loc[383, '작가'] = '노발리스'
datadf.loc[392, '작가'] = '알랭 로브그리예'
datadf.loc[404, '작가'] = '후안 룰포'

In [40]:
datadf[datadf['작가/번역'].str.contains('등저')]

,title,author,page,작가/번역,출판사,출간일,작가
1,한국단편문학선 1,김동인 등저 | 민음사 | 2000년 10월,http://www.yes24.com/Product/Goods/57202,김동인 등저,민음사,2000년 10월,
113,한국단편문학선 2,김동인 등저 | 민음사 | 1999년 03월,http://www.yes24.com/Product/Goods/57204,김동인 등저,민음사,1999년 03월,
244,한국 희곡선 1,"송영,허규 등저 / 양승국 편 | 민음사 | 2014년 02월",http://www.yes24.com/Product/Goods/12191539,"송영,허규 등저 / 양승국 편",민음사,2014년 02월,
245,한국 희곡선 2,"송영,허규 등저 / 양승국 편 | 민음사 | 2014년 02월",http://www.yes24.com/Product/Goods/12191542,"송영,허규 등저 / 양승국 편",민음사,2014년 02월,
412,세계문학전집 J세트 361-400 [ 전40권 ],"보리스 파스테르나크,제인 오스틴,미셸 투르니에,제인 오스틴,이디스 워튼 등저 / 김...",http://www.yes24.com/Product/Goods/108232965,"보리스 파스테르나크,제인 오스틴,미셸 투르니에,제인 오스틴,이디스 워튼 등저 / 김...",민음사,2022년 03월,
449,민음사 세계문학전집 세트 (250권),윌리엄 셰익스피어 등저 | 민음사 | 2011년 08월,http://www.yes24.com/Product/Goods/5468634,윌리엄 셰익스피어 등저,민음사,2011년 08월,
451,민음사 세계문학 전집 논술 세트 [ 전30권 ],"프란츠 카프카,조지 오웰,마크 트웨인 등저 / 전영애,도정일,김욱동 등역 | 민음사...",http://www.yes24.com/Product/Goods/4415708,"프란츠 카프카,조지 오웰,마크 트웨인 등저 / 전영애,도정일,김욱동 등역",민음사,2010년 11월,
452,민음사 세계문학전집 특별판 [ 전10권 ],"헤르만 헤세 저/마누엘 푸익 등저/송병선,전영애 등역 | 민음사 | 2009년 01월",http://www.yes24.com/Product/Goods/3265477,"헤르만 헤세 저/마누엘 푸익 등저/송병선,전영애 등역",민음사,2009년 01월,헤르만 헤세

In [41]:
# 등저 수동으로 입력~
datadf.loc[1, '작가'] = '김동인, 현진건, 이광수, 나도향, 최서해, 김유정, 채만식, 이상, 이효석, 이태준, 정비석, 염상섭'
datadf.loc[2, '작가'] = '김동리, 황순원, 오영수, 손창섭, 정한숙, 이호철, 장용학, 서기원, 박경리, 강신재, 선우휘'
datadf.loc[244, '작가'] = '송영, 유치진, 임선규, 함세덕, 오영진, 차범석, 이근삼, 박조열'
datadf.loc[245, '작가'] = '허규, 이현화, 오태석, 정복근, 이윤택, 김광림, 이만희, 이강백'

In [43]:
datadf.to_csv('./title-author_preprocessing.csv', index = False, encoding= 'utf-8-sig')